[workspace]

members = [
  "adder", "axum", "sullivan-tokio", "tokio", 
  "tutorial", "ude",
]
resolver = "2"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

